.TH "model/board.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/board.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'square\&.h'\fP
.br
\fC#include 'floodexception\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::Board\fP"
.br
.RI "The \fBBoard\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
