.TH "view/buttonwidget.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/buttonwidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QSignalMapper>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <model/color\&.h>\fP
.br
\fC#include 'colorConvert\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::ButtonWidget\fP"
.br
.RI "The \fBButtonWidget\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
