.TH "model/color.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/color.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBoli::Color\fP { \fBoli::Color::RED\fP, \fBoli::Color::GREEN\fP, \fBoli::Color::YELLOW\fP, \fBoli::Color::BLUE\fP, \fBoli::Color::PURPLE\fP, \fBoli::Color::DEEPPINK\fP, \fBoli::Color::CYAN\fP, \fBoli::Color::ORANGE\fP, \fBoli::Color::GREY\fP }
.RI "The Color enum This enumeration is used to set a color to a square\&. ""
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
