.TH "view/colorConvert.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/colorConvert.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QColor>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::ColorConvert\fP"
.br
.RI "The \fBColorConvert\fP class Class used by others class to convert a color to a QColor\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
