.TH "model/floodexception.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/floodexception.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::FloodException\fP"
.br
.RI "The \fBFloodException\fP class This is the exception class used for the game \&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
