.TH "model/HighScore.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/HighScore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QJsonObject>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::HighScore\fP"
.br
.RI "The \fBHighScore\fP class Used to compare old results and the new score according to the weight, the height and the number of colors function\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
