.TH "view/intro.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/intro.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QPalette>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntro\fP"
.br
.RI "The \fBIntro\fP class The class launched during a few seconds at the begining of the program launch\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
