.TH "view/mainwindow.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QStackedWidget>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include 'widgetGame\&.h'\fP
.br
\fC#include 'intro\&.h'\fP
.br
\fC#include 'menustart\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'reset\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "The \fBMainWindow\fP class The application's controller This class manage the different view of the application and the has the game object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
