.TH "observer/observable.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
observer/observable.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'observer\&.h'\fP
.br
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::Observable\fP"
.br
.RI "The \fBObservable\fP class Interface implemented by the classes that have to be observed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
