.TH "view/reset.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/reset.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QPushButton>\fP
.br
\fC#include <QHBoxLayout>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReset\fP"
.br
.RI "The \fBReset\fP class To confirm reseting of the scores record\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
