.TH "Reset" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reset \- The \fBReset\fP class To confirm reseting of the scores record\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reset\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReset\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Reset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBReset\fP class To confirm reseting of the scores record\&. 
.PP
Definition at line 14 of file reset\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Reset::Reset (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 3 of file reset\&.cpp\&.
.PP
.nf
4 {
5 
6 }
.fi
.SS "Reset::~Reset ()"

.PP
Definition at line 26 of file reset\&.cpp\&.
.PP
.nf
26 {}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
