.TH "view/viewboard.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/viewboard.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QLabel>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include 'observer/observer\&.h'\fP
.br
\fC#include 'model/floodgame\&.h'\fP
.br
\fC#include 'buttonwidget\&.h'\fP
.br
\fC#include 'colorConvert\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBoli::ViewBoard\fP"
.br
.RI "The \fBViewBoard\fP class the class that create and refresh the game's board view\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoli\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
