.TH "view/widgetGame.h" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/widgetGame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QStackedWidget>\fP
.br
\fC#include 'view/viewboard\&.h'\fP
.br
\fC#include 'model/floodgame\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWidgetGame\fP"
.br
.RI "The \fBWidgetGame\fP class the widget containing the game's view\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
