.TH "view/widgetGame.cpp" 3 "Thu Oct 19 2017" "Version Flood It by Olivier Cordier" "Flood it" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/widgetGame.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'widgetGame\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Flood it from the source code\&.
